import { PexelsImage } from "../types";

const mockImagesPage1: PexelsImage[] = [
  {
    id: 1,
    alt: "Image 1",
    avg_color: "#d4d4d4",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 1",
    photographer_id: 123,
    photographer_url: "https://www.pexels.com/@photographer1",
    src: {
      original: "image1.jpg",
      large2x: "image1_large2x.jpg",
      large: "image1_large.jpg",
      medium: "image1_medium.jpg",
      small: "image1_small.jpg",
      portrait: "image1_portrait.jpg",
      landscape: "image1_landscape.jpg",
      tiny: "image1_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/1",
  },
  {
    id: 2,
    alt: "Image 2",
    avg_color: "#f1f1f1",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 2",
    photographer_id: 456,
    photographer_url: "https://www.pexels.com/@photographer2",
    src: {
      original: "image2.jpg",
      large2x: "image2_large2x.jpg",
      large: "image2_large.jpg",
      medium: "image2_medium.jpg",
      small: "image2_small.jpg",
      portrait: "image2_portrait.jpg",
      landscape: "image2_landscape.jpg",
      tiny: "image2_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/2",
  },
  {
    id: 3,
    alt: "Image 3",
    avg_color: "#d3d3d3",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 3",
    photographer_id: 789,
    photographer_url: "https://www.pexels.com/@photographer3",
    src: {
      original: "image3.jpg",
      large2x: "image3_large2x.jpg",
      large: "image3_large.jpg",
      medium: "image3_medium.jpg",
      small: "image3_small.jpg",
      portrait: "image3_portrait.jpg",
      landscape: "image3_landscape.jpg",
      tiny: "image3_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/3",
  },
  {
    id: 4,
    alt: "Image 4",
    avg_color: "#f2f2f2",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 4",
    photographer_id: 101112,
    photographer_url: "https://www.pexels.com/@photographer4",
    src: {
      original: "image4.jpg",
      large2x: "image4_large2x.jpg",
      large: "image4_large.jpg",
      medium: "image4_medium.jpg",
      small: "image4_small.jpg",
      portrait: "image4_portrait.jpg",
      landscape: "image4_landscape.jpg",
      tiny: "image4_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/4",
  },
  {
    id: 5,
    alt: "Image 5",
    avg_color: "#cccccc",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 5",
    photographer_id: 131415,
    photographer_url: "https://www.pexels.com/@photographer5",
    src: {
      original: "image5.jpg",
      large2x: "image5_large2x.jpg",
      large: "image5_large.jpg",
      medium: "image5_medium.jpg",
      small: "image5_small.jpg",
      portrait: "image5_portrait.jpg",
      landscape: "image5_landscape.jpg",
      tiny: "image5_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/5",
  },
  {
    id: 6,
    alt: "Image 6",
    avg_color: "#bbbbbb",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 6",
    photographer_id: 161718,
    photographer_url: "https://www.pexels.com/@photographer6",
    src: {
      original: "image6.jpg",
      large2x: "image6_large2x.jpg",
      large: "image6_large.jpg",
      medium: "image6_medium.jpg",
      small: "image6_small.jpg",
      portrait: "image6_portrait.jpg",
      landscape: "image6_landscape.jpg",
      tiny: "image6_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/6",
  },
  {
    id: 7,
    alt: "Image 7",
    avg_color: "#aaaaaa",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 7",
    photographer_id: 192021,
    photographer_url: "https://www.pexels.com/@photographer7",
    src: {
      original: "image7.jpg",
      large2x: "image7_large2x.jpg",
      large: "image7_large.jpg",
      medium: "image7_medium.jpg",
      small: "image7_small.jpg",
      portrait: "image7_portrait.jpg",
      landscape: "image7_landscape.jpg",
      tiny: "image7_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/7",
  },
  {
    id: 8,
    alt: "Image 8",
    avg_color: "#999999",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 8",
    photographer_id: 222324,
    photographer_url: "https://www.pexels.com/@photographer8",
    src: {
      original: "image8.jpg",
      large2x: "image8_large2x.jpg",
      large: "image8_large.jpg",
      medium: "image8_medium.jpg",
      small: "image8_small.jpg",
      portrait: "image8_portrait.jpg",
      landscape: "image8_landscape.jpg",
      tiny: "image8_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/8",
  },
  {
    id: 9,
    alt: "Image 9",
    avg_color: "#888888",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 9",
    photographer_id: 252627,
    photographer_url: "https://www.pexels.com/@photographer9",
    src: {
      original: "image9.jpg",
      large2x: "image9_large2x.jpg",
      large: "image9_large.jpg",
      medium: "image9_medium.jpg",
      small: "image9_small.jpg",
      portrait: "image9_portrait.jpg",
      landscape: "image9_landscape.jpg",
      tiny: "image9_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/9",
  },
  {
    id: 10,
    alt: "Image 10",
    avg_color: "#777777",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 10",
    photographer_id: 282930,
    photographer_url: "https://www.pexels.com/@photographer10",
    src: {
      original: "image10.jpg",
      large2x: "image10_large2x.jpg",
      large: "image10_large.jpg",
      medium: "image10_medium.jpg",
      small: "image10_small.jpg",
      portrait: "image10_portrait.jpg",
      landscape: "image10_landscape.jpg",
      tiny: "image10_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/10",
  },
  {
    id: 11,
    alt: "Image 11",
    avg_color: "#666666",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 11",
    photographer_id: 313233,
    photographer_url: "https://www.pexels.com/@photographer11",
    src: {
      original: "image11.jpg",
      large2x: "image11_large2x.jpg",
      large: "image11_large.jpg",
      medium: "image11_medium.jpg",
      small: "image11_small.jpg",
      portrait: "image11_portrait.jpg",
      landscape: "image11_landscape.jpg",
      tiny: "image11_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/11",
  },
  {
    id: 12,
    alt: "Image 12",
    avg_color: "#555555",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 12",
    photographer_id: 343536,
    photographer_url: "https://www.pexels.com/@photographer12",
    src: {
      original: "image12.jpg",
      large2x: "image12_large2x.jpg",
      large: "image12_large.jpg",
      medium: "image12_medium.jpg",
      small: "image12_small.jpg",
      portrait: "image12_portrait.jpg",
      landscape: "image12_landscape.jpg",
      tiny: "image12_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/12",
  },
];

const mockImagesPage2: PexelsImage[] = [
  {
    id: 13,
    alt: "Image 13",
    avg_color: "#444444",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 13",
    photographer_id: 373839,
    photographer_url: "https://www.pexels.com/@photographer13",
    src: {
      original: "image13.jpg",
      large2x: "image13_large2x.jpg",
      large: "image13_large.jpg",
      medium: "image13_medium.jpg",
      small: "image13_small.jpg",
      portrait: "image13_portrait.jpg",
      landscape: "image13_landscape.jpg",
      tiny: "image13_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/13",
  },
  {
    id: 14,
    alt: "Image 14",
    avg_color: "#333333",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 14",
    photographer_id: 404142,
    photographer_url: "https://www.pexels.com/@photographer14",
    src: {
      original: "image14.jpg",
      large2x: "image14_large2x.jpg",
      large: "image14_large.jpg",
      medium: "image14_medium.jpg",
      small: "image14_small.jpg",
      portrait: "image14_portrait.jpg",
      landscape: "image14_landscape.jpg",
      tiny: "image14_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/14",
  },
  {
    id: 15,
    alt: "Image 15",
    avg_color: "#222222",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 15",
    photographer_id: 454647,
    photographer_url: "https://www.pexels.com/@photographer15",
    src: {
      original: "image15.jpg",
      large2x: "image15_large2x.jpg",
      large: "image15_large.jpg",
      medium: "image15_medium.jpg",
      small: "image15_small.jpg",
      portrait: "image15_portrait.jpg",
      landscape: "image15_landscape.jpg",
      tiny: "image15_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/15",
  },
  {
    id: 16,
    alt: "Image 16",
    avg_color: "#111111",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 16",
    photographer_id: 484950,
    photographer_url: "https://www.pexels.com/@photographer16",
    src: {
      original: "image16.jpg",
      large2x: "image16_large2x.jpg",
      large: "image16_large.jpg",
      medium: "image16_medium.jpg",
      small: "image16_small.jpg",
      portrait: "image16_portrait.jpg",
      landscape: "image16_landscape.jpg",
      tiny: "image16_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/16",
  },
  {
    id: 17,
    alt: "Image 17",
    avg_color: "#888888",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 17",
    photographer_id: 515253,
    photographer_url: "https://www.pexels.com/@photographer17",
    src: {
      original: "image17.jpg",
      large2x: "image17_large2x.jpg",
      large: "image17_large.jpg",
      medium: "image17_medium.jpg",
      small: "image17_small.jpg",
      portrait: "image17_portrait.jpg",
      landscape: "image17_landscape.jpg",
      tiny: "image17_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/17",
  },
  {
    id: 18,
    alt: "Image 18",
    avg_color: "#777777",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 18",
    photographer_id: 545556,
    photographer_url: "https://www.pexels.com/@photographer18",
    src: {
      original: "image18.jpg",
      large2x: "image18_large2x.jpg",
      large: "image18_large.jpg",
      medium: "image18_medium.jpg",
      small: "image18_small.jpg",
      portrait: "image18_portrait.jpg",
      landscape: "image18_landscape.jpg",
      tiny: "image18_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/18",
  },
  {
    id: 19,
    alt: "Image 19",
    avg_color: "#666666",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 19",
    photographer_id: 575859,
    photographer_url: "https://www.pexels.com/@photographer19",
    src: {
      original: "image19.jpg",
      large2x: "image19_large2x.jpg",
      large: "image19_large.jpg",
      medium: "image19_medium.jpg",
      small: "image19_small.jpg",
      portrait: "image19_portrait.jpg",
      landscape: "image19_landscape.jpg",
      tiny: "image19_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/19",
  },
  {
    id: 20,
    alt: "Image 20",
    avg_color: "#555555",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 20",
    photographer_id: 606162,
    photographer_url: "https://www.pexels.com/@photographer20",
    src: {
      original: "image20.jpg",
      large2x: "image20_large2x.jpg",
      large: "image20_large.jpg",
      medium: "image20_medium.jpg",
      small: "image20_small.jpg",
      portrait: "image20_portrait.jpg",
      landscape: "image20_landscape.jpg",
      tiny: "image20_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/20",
  },
  {
    id: 21,
    alt: "Image 21",
    avg_color: "#444444",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 21",
    photographer_id: 636465,
    photographer_url: "https://www.pexels.com/@photographer21",
    src: {
      original: "image21.jpg",
      large2x: "image21_large2x.jpg",
      large: "image21_large.jpg",
      medium: "image21_medium.jpg",
      small: "image21_small.jpg",
      portrait: "image21_portrait.jpg",
      landscape: "image21_landscape.jpg",
      tiny: "image21_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/21",
  },
  {
    id: 22,
    alt: "Image 22",
    avg_color: "#333333",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 22",
    photographer_id: 676869,
    photographer_url: "https://www.pexels.com/@photographer22",
    src: {
      original: "image22.jpg",
      large2x: "image22_large2x.jpg",
      large: "image22_large.jpg",
      medium: "image22_medium.jpg",
      small: "image22_small.jpg",
      portrait: "image22_portrait.jpg",
      landscape: "image22_landscape.jpg",
      tiny: "image22_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/22",
  },
  {
    id: 23,
    alt: "Image 23",
    avg_color: "#222222",
    height: 800,
    width: 600,
    liked: false,
    photographer: "Photographer 23",
    photographer_id: 707172,
    photographer_url: "https://www.pexels.com/@photographer23",
    src: {
      original: "image23.jpg",
      large2x: "image23_large2x.jpg",
      large: "image23_large.jpg",
      medium: "image23_medium.jpg",
      small: "image23_small.jpg",
      portrait: "image23_portrait.jpg",
      landscape: "image23_landscape.jpg",
      tiny: "image23_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/23",
  },
  {
    id: 24,
    alt: "Image 24",
    avg_color: "#111111",
    height: 600,
    width: 800,
    liked: true,
    photographer: "Photographer 24",
    photographer_id: 737475,
    photographer_url: "https://www.pexels.com/@photographer24",
    src: {
      original: "image24.jpg",
      large2x: "image24_large2x.jpg",
      large: "image24_large.jpg",
      medium: "image24_medium.jpg",
      small: "image24_small.jpg",
      portrait: "image24_portrait.jpg",
      landscape: "image24_landscape.jpg",
      tiny: "image24_tiny.jpg",
    },
    url: "https://www.pexels.com/photo/24",
  },
];

export { mockImagesPage1, mockImagesPage2 };
